### ISSUE TITLE
Adjust "MANDATORY" in csv file and script

### ISSUE THREAD

**Issue by ISEALElizabeth** [ISEAL-Community/iseal-core#12]
In the iseal-core.csv file change MANDATORY to mandatory.  Will also need to adjust the program script to recognize this change.

**Comment by ISEALElizabeth** [comment]
Alan, This is associated with reviewing use of capitals in the CSV file.  Will you still complete this task?

**Comment by alanorth** [comment]
@ISEALElizabeth I would like to, yes. I will try to find time in the next week.
