### ISSUE TITLE
Add contact information for ICMS and FSC extension

### ISSUE THREAD

**Issue by ISEALElizabeth** [ISEAL-Community/iseal-core#22]
Under "Feedback" section for the ICMS, please list "Elizabeth Kennedy (elizabeth@isealalliance.org)".  

For the FSC extension pages, under "Feedback" section, please list "Benjamin Kimuri (b.kimuri@fsc.org)".

**Comment by alicevthompson** [comment]
Contact details added for FSC schema and ICMS.
