### ISSUE TITLE
Make it easier to find required metadata elements in documentation site

### ISSUE THREAD

**Issue by alanorth** [ISEAL-Community/iseal-core#6]
I'm not sure about how we present this, perhaps grouping required metadata elements together or having some kind of toggle/filter function.

**Comment by ISEALElizabeth** [comment]
Alan suggests java script with 1/2 day timeframe. There are some other alternatives.  Could feasibly re-color the buttons.

**Comment by alanorth** [comment]
Suggestion from @adamISEAL was to simply add a style to the element's button where we group them under each module. Much easier than writing custom JavaScript to filter them! I have styled the required elements with the same red used in the "required" badges.

![Screenshot 2022-02-14 at 21-33-41 ISEAL Core Metadata Set-fs8](https://user-images.githubusercontent.com/191754/153927739-d0dba511-10c2-4477-9941-ce48fd770881.png)

The styles themselves are defined in `site/source/scss/iseal.scss` and `site/source/scss/fsc.scss` and the logic for the buttons is in `site/layouts/partials/module-elements.html`.
